services:
  web:
    build: ./web
    container_name: desafio3-web
    ports:
      - "8080:8080"
    depends_on:
      - db
      - cache
    environment:
      - DB_HOST=db
      - DB_NAME=mydb
      - DB_USER=user
      - DB_PASSWORD=password
      - CACHE_HOST=cache
    networks:
      - minha_rede

  db:
    image: postgres:15
    container_name: desafio3-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - minha_rede

  cache:
    image: redis:7
    container_name: desafio3-cache
    networks:
      - minha_rede

networks:
  minha_rede:
    driver: bridge

volumes:
  db_data:
